### ISSUE TITLE
Seeder not completed 

### ISSUE THREAD

**Issue by antenemy** [bagisto/laravel-data-faker#12]
stucked in:

Seeding: Webkul\DataFaker\Database\Seeders\CustomerAddressTableDataSeeder
Seeded:  Webkul\DataFaker\Database\Seeders\CustomerAddressTableDataSeeder (1.05 seconds)
Seeding: Webkul\DataFaker\Database\Seeders\ProductCategoryTableDataSeeder
Seeded:  Webkul\DataFaker\Database\Seeders\ProductCategoryTableDataSeeder (0.04 seconds)
Seeding: Webkul\DataFaker\Database\Seeders\ProductTableDataSeeder

version:

php artisan bagisto:version
v1.2.0

**Comment by naresh-webkul** [comment]
it looks like seeder is still seeding the products related data,
it may take some time to complete seeding process depend on your products count that you have provided in the seeder.

**Comment by ghermans** [comment]
I confirm that there is a issue with seeding products, i started the database seeder 5minutes ago, and only now it has 3 products in the database. this takes too long.
