### ISSUE TITLE
Upgrade for Laravel 8 and bagisto 1.3.0

### ISSUE THREAD

**Issue by akristou** [bagisto/laravel-data-faker#13]
Seed command not work with Bagisto 1.3.0 and Laravel 8:
php artisan db:seed --class="Webkul\DataFaker\Database\Seeders\DatabaseSeeder"

We have this error:
Unable to locate factory for [Webkul\Product\Models\ProductFlat].

**Comment by AbdElrahmaN31** [comment]
@ghermans Excuse me, when can you expect to solve this bug?

**Comment by devansh-webkul** [comment]
Unfortunately, the latest version is on Laravel 8 and currently, this is not compatible. But your problem seems to be here,
https://github.com/bagisto/laravel-data-faker/blob/f952fa75ed6990e1bac5233943245c74ed79c631/composer.json#L26

**Comment by abdelrahman-varit** [comment]
> Unfortunately, the latest version is on Laravel 8 and currently, this is not compatible. But your problem seems to be here,
> https://github.com/bagisto/laravel-data-faker/blob/f952fa75ed6990e1bac5233943245c74ed79c631/composer.json#L26
> 
> Just try to fix your composer autoload.

I found the factory dir is with capital D in Database and updated it but the same error

**Comment by AbdElrahmaN31** [comment]
> Unfortunately, the latest version is on Laravel 8 and currently, this is not compatible. But your problem seems to be here,
> https://github.com/bagisto/laravel-data-faker/blob/f952fa75ed6990e1bac5233943245c74ed79c631/composer.json#L26
> 
> Just try to fix your composer autoload.

I checked the factory dir and found it with capital D in Database and updated it, but nothing changed. still reduce the same error

**Comment by AbdElrahmaN31** [comment]
@devansh-webkul Excuse me, can you give my any hint, how I can solve this issue?

**Comment by devansh-webkul** [comment]
May i know what version of composer are you using?

**Comment by devansh-webkul** [comment]
And one more thing I want to mention. Version 1.3.0 is not on Laravel 8.

**Comment by AbdElrahmaN31** [comment]
> May i know what version of composer are you using?

Thanks for replaying @devansh-webkul . My Composer version is 2.1.5.

**Comment by AbdElrahmaN31** [comment]
> And one more thing I want to mention. Version 1.3.0 is not on Laravel 8,
> https://github.com/bagisto/bagisto/blob/87d933648df2d80458df54622b1a6c065b7b7328/composer.json#L37
@devansh-webkul 
Also my bagisto vesion is 1.3.2

**Comment by devansh-webkul** [comment]
In that case, this will not work in your instance. I am marking this as an enhancement because this needs to be compatible. In your case, I just only recommend you to wait for this.

**Comment by AbdElrahmaN31** [comment]
@devansh-webkul Thanks. Is there any other way to create dummy products?

**Comment by devansh-webkul** [comment]
Right now there is no way. Unless and until you can create your own script. But I recommend you to wait for this. Because even if you do changes in the vendor this will get overwritten and this is not recommendable.

**Comment by AbdElrahmaN31** [comment]
> Right now there is no way. Unless and until you can create your own script. But I recommend you to wait for this. Because even if you do changes in the vendor this will get overwritten and this is not recommendable.

@devansh-webkul Thanks a lot for your replaying and helping. when can we guess get this enhancement?

**Comment by devansh-webkul** [comment]
Hi @AbdElrahmaN31,

I just checked this and currently, it is not met with the Laravel 8 complaints. So I am giving the quick fix for this.

Then, after that, we will improve the core first. Then again back to this one.

**Comment by devansh-webkul** [comment]
Raised an issue to core for update the laravel factories also,
https://github.com/bagisto/bagisto/issues/5165

**Comment by abdelrahman-varit** [comment]
@devansh-webkul , Thanks a lot

**Comment by AbdElrahmaN31** [comment]
@devansh-webkul , Thanks a lot

**Comment by AbdElrahmaN31** [comment]
@devansh-webkul It works well, but simple products don't return at website, admin or api, although when I open the product in admin though links like this `/admin/catalog/products/edit/32` and click save product without any changes the product appear!

**Comment by ghermans** [comment]
Closing this issue as it will be followed up with #24
