### ISSUE TITLE
File path for ProductFlat seems to be wrong

### ISSUE THREAD

**Issue by teoyi** [bagisto/laravel-data-faker#17]
Hi! I am currently setting up bagisto for a test phase for an ecommerce site. 

While trying to populate the database with dummy data, I realize that there might be an issue with the file path for ProductFlat while using the db:seed command. 

Do see attached image of my attempt at moving the files to fulfill the path needed for db:seed to run. It appears ProductFlat is the only one without a `\src\` directory path included.

Kindly note that the second db:seed command is when I moved the Model files out of the `src` directory and into the `\Product\` directory.
 
![image](https://user-images.githubusercontent.com/67887422/133402245-e6081457-e2ca-412f-ac32-ec52b4f5fa0c.png)

**Comment by AbdElrahmaN31** [comment]
Same error with me

> In FactoryBuilder.php line 273:
                                                                      
  Unable to locate factory for [Webkul\Product\Models\ProductImage].

**Comment by AbdElrahmaN31** [comment]
If you can help, it would be appreciated @vivek-webkul @jitendra-webkul

**Comment by ghermans** [comment]
Duplicated issue #13
