### ISSUE TITLE
Error on seeding

### ISSUE THREAD

**Issue by davymaish** [bagisto/laravel-data-faker#21]
Latest version of Bagisto v0.2.0

``
In Connection.php line 678:

  SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_c
  i,IMPLICIT) for operation '=' (SQL: update `categories` set `_rgt` = 26 where `categories`.`id` = 1)

In Exception.php line 18:

  SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_c
  i,IMPLICIT) for operation '='

In PDOStatement.php line 112:

  SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_c
  i,IMPLICIT) for operation '='

**Comment by hashirhamxa** [comment]
@davymaish is it solved?

**Comment by jitendra-webkul** [comment]
Fixed in #27 (Brand new faker)
