### ISSUE TITLE
Call to undefined function Webkul\DataFaker\Database\Seeders\factory() 

### ISSUE THREAD

**Issue by ghermans** [bagisto/laravel-data-faker#23]
## Steps to reproduce
Run php artisan db:seed --class="Webkul\DataFaker\Database\Seeders\DatabaseSeeder"

## Actual result 
Seeding: Webkul\DataFaker\Database\Seeders\CustomerAddressTableDataSeeder

In CustomerAddressTableDataSeeder.php line 16:
                                                                          
  Call to undefined function Webkul\DataFaker\Database\Seeders\factory()

**Comment by jitendra-webkul** [comment]
Fixed in #27 (Brand new faker)
