### ISSUE TITLE
categories fake data

### ISSUE THREAD

**Issue by MohamedAbdElghani** [bagisto/laravel-data-faker#28]
Class Database\Factories\Webkul\Category\Models\CategoryTranslationFactory  not found

**Comment by jitendra-webkul** [comment]
Please use the Bagisto master

**Comment by abdallahnasar** [comment]
> Please use the Bagisto master

Hello I am facing the same issue, although using Bagisto master.

**Comment by abdallahnasar** [comment]
Hello,

I tried solving the issue as I didn't find CategoryTranslationFactory class even in the vendors directory, so as a workaround I created file: CategoryTranslationFactory.php at {base_dir}/database/factories/Webkul/Category/Models/CategoryTranslationFactory.php 
(with creating folders for Webkul, Category, Models ) to apply  psr-4 autoloading standards: with the below code:

`<?php
namespace Database\Factories\Webkul\Category\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Webkul\Category\Models\CategoryTranslation;

class CategoryTranslationFactory extends Factory
{

    protected $model = CategoryTranslation::class;

    public function definition()
    {
        return [
            'locale'                       => 'en',
            'name'                        => $this->faker->word,
        ];
    }
}
`

then run:
composer dump-autoload 
php artisan optimize:clear

and then everything works fine
