### ISSUE TITLE
Job batch doesn't exist

### ISSUE THREAD

**Issue by istiaqahmed121998** [bagisto/laravel-data-faker#29]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.job_batches' doesn't exist   
  (SQL: insert into `job_batches` (`id`, `name`, `total_jobs`, `pending_jobs`, `failed_jobs`, `f  
  ailed_job_ids`, `options`, `created_at`, `cancelled_at`, `finished_at`) values (97a3e995-2650-  
  48c4-a6a7-ef940b277a16, , 0, 0, 0, [], a:0:{}, 1667302543, ?, ?))

**Comment by jitendra-webkul** [comment]
Please run the following command to generate job migrations

php artisan queue:batches-table

php artisan migrate
