### ISSUE TITLE
Class 'Database\Factories\Webkul\Category\Models\CategoryTranslationFactory' not found

### ISSUE THREAD

**Issue by hagarwal-velsof** [bagisto/laravel-data-faker#41]
Hi,

I am facing the following error after running php artisan bagisto:fake -

Class 'Database\Factories\Webkul\Category\Models\CategoryTranslationFactory' not found
![bagisto-error1](https://github.com/bagisto/laravel-data-faker/assets/58728963/78db9689-8dda-40e4-a5df-cb7114d6fb70)

**Comment by jeann2013** [comment]
me too

**Comment by shivendra-webkul** [comment]
Hi @hagarwal-velsof, Could you please specify in which version you are facing this problem? This will help us investigate and address the issue more effectively. Thank you!
I have checked it in master, this issue not appearing I attached screenshot please check it. 
![screenshot_from_2024_02_09_11_39_15](https://github.com/bagisto/laravel-data-faker/assets/121868701/9f1f4def-5a81-41f5-ba21-2b8df415b5f1)

**Comment by hagarwal-velsof** [comment]
Hi,

I am facing it in Bagisto version 1.4.1

[image: image.png]

--

Thanks & Regards
Harsh Agarwal
Velocity Software Solutions Pvt. Ltd.
E-23, Sector 63, Noida – 201 301
*Ph:* +91-120-424 3310   *Mob:* +91-962 523 5181, +91-782 733 6579
*Website:* www.velsof.com

**Comment by shivendra-webkul** [comment]
Hi @hagarwal-velsof, Could you please specify in which version you are facing this problem? This will help us investigate and address the issue more effectively. Thank you!
I have checked it in master, this issue not appearing I attached screenshot please check it.
![image](https://github.com/bagisto/laravel-data-faker/assets/121868701/66ea7c26-279a-4f0c-878f-0a3a220f047e)

**Comment by hagarwal-velsof** [comment]
![image](https://github.com/bagisto/laravel-data-faker/assets/58728963/05345552-2caa-460d-b9ab-f0a4133e88d3)

I am facing it in Version 1.4.1

**Comment by jitendra-webkul** [comment]
Database\Factories\Webkul\Category\Models\CategoryTranslationFactory class is not present in version 1.4.1. You can either upgrade to a later version that includes this class or manually add the class if needed.
