### ISSUE TITLE
Class 'Webkul\DataFaker\DataFakerServiceProvider' not found

### ISSUE THREAD

**Issue by cheetaof71** [bagisto/laravel-data-faker#8]
When I try to setup laravel-data-faker it shows me these error,

In ProviderRepository.php line 208:

  Class 'Webkul\DataFaker\DataFakerServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by GiovanniMounir** [comment]
I had the same issue: there is a typo in the file `DatbaseSeeder.php`; renaming it to `DatabaseSeeder.php` fixed the problem for me.
